### ISSUE TITLE
Wrong number of QROUNDS in block encryption

### ISSUE THREAD

**Issue by rilysh** [Ginurx/chacha20-c#4]
Hi,
According to [RFC7539](https://datatracker.ietf.org/doc/html/rfc7539#section-2.3) ChaCha20 implements 10 iteration in 2 rounds (simply 20 rounds in total). However, this implementation uses 10 rounds to do `CHACHA20_QUARTERROUND`.

https://github.com/Ginurx/chacha20-c/blob/78caf6667107f12f0997476f2c171e23a0b601c0/chacha20.c#L70

I haven't yet tested it, though.

**Comment by ivop** [comment]
If you look at the body of the for-loop you'll notice that each word is updated twice, and 10*2=20.
See openssl which does: for (i = 20; i > 0; i -= 2) { ```/* eight macro expansions */``` }. Note the -=2.

**Comment by rilysh** [comment]
Indeed, sorry, I actually didn't noticed that earlier, so missed it. Thanks for the heads up! @ivop
